"""empty message

Revision ID: 9578ad57e964
Revises: f69e92b3e58e
Create Date: 2023-01-04 12:02:26.194985

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9578ad57e964'
down_revision = 'f69e92b3e58e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.String(length=128), nullable=False),
                    sa.Column('email', sa.String(length=128), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
